---
title: "EDA Student Performance prediction"
Github Link: 
---
Link to the dataset: https://archive.ics.uci.edu/ml/datasets/student+performance
two dataset: student-mat.csv (Math course) and student-por.csv (Portuguese language course) 

```{r}
library(readr)
library(tidyverse)
```


```{r}
#### Math dataset
student_mat<- read.table("student-mat.csv", header =TRUE, sep = ";", stringsAsFactors = T)
student_mat$class<- as.factor("mat")

#### Por language dataset
student_por<- read.table("student-por.csv", header =TRUE, sep=";", stringsAsFactors = T)
student_por$class<- as.factor("por")

#### combine the two dataset
student<-rbind(student_mat,student_por)
student<-student[c(1:30,34,31:33)]

#save the combined dataset
# write.csv(student,'student2.csv')

summary(student)
str(student)

```


```{r}
attribute<-c("School","Sex","Age","Address","Family Size","Parent's Status","Mother Education","Father Education","Mother Job","Father Job" ,"Reason","guardian","Time to Travel to School","Weekly Study Time","Past Class Failures","School Educational Support","Family Educational Support"," Extra Paid Class", "Extra Curricular Activities", "Attended Nursery School","Want to Take Higher Education","Internet Access at Home","With a Romantic Relationship","Quality of Family Relationships","Free Time after School","Going out with Friends ","Workday Alcohol Consumption", "Weekend Alcohol Consumption", "Current Health Status","Number of School Absences ","Class", "First Period Grade",  "Secound Period Grade","Final Grade")
### Distributions for all Attributes
for( i in 1:34){
print(ggplot(student,aes(student[,i],fill=factor(student[,i])))+ geom_bar()+facet_wrap(~class)+xlab(names(student[i]))+xlab(attribute[i]))
}

#The G1,G2,G3 distributions show a normal distribution except for students who score zero. these outliers we have to study them and find insights about them and how they will affects our model.
```
 
```{r}
# Subsetting student who got 0 in g3
student0<-student[which(student$G3==0),]

#  student who got 0 in G3 Visualization 
for( i in 1:32){
print(ggplot(student0,aes(factor(student0[,i]),fill=factor(student0[,i])))+ geom_bar()+facet_wrap(~class)+xlab(names(student0[i]))+xlab(attribute[i]))
}
#####################################
# EDA for the group of the students who score zero in the final grade
####################################
# GP: there are around 35 students got 0 of 350 10% students in math where for por  3 students 420 0.7% less than 1%
# MS: 4 students out of 50 in math 8% where por 14 students of 230 6%
########################################
#more female students got zero in math when there is almost the same number of students
#less female students got zero in por even there were more female students in por course than male
########################################
# Even the number of students in math is less than those in por , the failure is higher. and the age in math is less than por for this group of students.
#######################################
#there are students who got zero in the final grade even they got marks between 4 and 12 in the first math exam and between 4-11 in por ,on the other hand the range of marks in the second exam was between 0 and 10  in math and  0 and 9 in por. that might indicate that there are other factors than the grades in first and second exams as in first exam the minimum grade was 4  
#########################################
# Most of the students in this group didn't have previous failure in math course where in por the maximum was failing one time.
#########################################
#  The health of this group of students was good with few have bad to very bad health.
#############
#The students in this group did not have any absences.


```

```{r}
# Subsetting student. removing students who score zero g3 and did not score zero in g1 and g2 as this group might have other factor that make them score zero in g3
student_sub0<-student[which(student$G3==0 & student$G1!=0 & student$G2!=0),]
for( i in c(11,15,30, 32,33)){
print(ggplot(student_sub0,aes(factor(student_sub0[,i]),fill=factor(student_sub0[,i])))+ geom_bar()+facet_wrap(~class)+xlab(names(student_sub0[i]))+xlab(attribute[i]))
}
```


```{r}
# Subsetting student who did not got 0 in g3
student_not0<-student[which(student$G3 !=0),]
for( i in 31:34){
print(ggplot(student_not0,aes(factor(student_not0[,i]),fill=factor(student_not0[,i])))+ geom_bar()+facet_wrap(~class)+xlab(names(student_not0[i]))+xlab(attribute[i]))
}

### the students distribution for the students who did not score 0 in final grade G3.
```
```{r}

# plotting the attributes vs G3
for( i in 1:33){
print(ggplot(student,aes(student[,i],G3))+ geom_point()+facet_wrap(~class)+xlab(names(student[i]))+xlab(attribute[i]))
}

```


```{r}
# plotting the attributes vs G1
for( i in c(30,33,34)){
print(ggplot(student,aes(student[,i],G1))+ geom_point()+facet_wrap(~class)+xlab(names(student[i]))+xlab(attribute[i]))
}

```




```{r}
## The group of students who score between 10-15(EDA)
## Subsetting student who get 10-15
student_pass1<-student[which(student$G3==10:15),]
for( i in c(30,32,33,34)){
print(ggplot(student_pass1,aes(factor(student_pass1[,i]),fill=factor(student_pass1[,i])))+ geom_bar()+facet_wrap(~class)+xlab(names(student_pass1[i]))+xlab(attribute[i]))
}

# the score for this group in G1 and G2 were between 7 and 16.

```

```{r}
# Subsetting student who get 16-18
student_pass2<-student[which(student$G3==16:18),]

for( i in c(30,32,33,34)){
print(ggplot(student_pass2,aes(factor(student_pass2[,i]),fill=factor(student_pass2[,i])))+ geom_bar()+facet_wrap(~class)+xlab(names(student_pass2[i]))+xlab(attribute[i]))
}
# students scored in G1 between 10 to 18 and in G2 10 and 18.
# Subsetting student who get 19-20
student_pass3<-student[which(student$G3==19:20),]
for( i in c(30,32,33,34)){
print(ggplot(student_pass3,aes(factor(student_pass3[,i]),fill=factor(student_pass3[,i])))+ geom_bar()+facet_wrap(~class)+xlab(names(student_pass3[i]))+xlab(attribute[i]))
}
### students scored in G1 16,18,19 and in G2 18,19. maximum absences was 6 
```
```{r}
for( i in c(3,7,8,13,14,24:30,32:34)){
print(ggplot(student,aes(student[,i],fill=class))+ geom_boxplot()+xlab(attribute[i]))
}
```

```{r fig.height=25, fig.width=50}
library(corrplot)
num<-sapply(student, is.numeric)
numeric<-student[,num]
cor_numeric<-cor(numeric, method = "pearson")
corrplot.mixed(cor_numeric,upper ="number",lower="color")   ### library(corrplot)
### There are high positive corrolations between G1, G2 and G3.
```

```{r}
student_num<-sapply(student, as.integer)
cor_student<-cor(student_num, method = "spearman")
corrplot.mixed(cor_student,upper ="number",lower="color")   ### library(corrplot)
### There are high positive corrolations between G1, G2 and G3.
```